# Generated by Django 4.2.15 on 2024-08-30 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0006_alter_ratingstar_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Загаловок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('video', models.FileField(upload_to='MovieVideo/%Y/%m/%d', verbose_name='Видео')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='фильм')),
            ],
            options={
                'verbose_name': 'Видео Файл',
                'verbose_name_plural': 'Видео Файлы',
            },
        ),
    ]
