# Generated by Django 4.2.15 on 2024-08-30 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_ratingstar_options'),
        ('movies_and_shows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to='Video/%Y/%m/%d', verbose_name='Видео'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.PositiveSmallIntegerField(default=1, verbose_name='Сезон')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='season', to='movies.movie', verbose_name='Сериал')),
            ],
            options={
                'verbose_name': 'Сезон',
                'verbose_name_plural': 'Сезоны',
            },
        ),
        migrations.AddField(
            model_name='video',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='epsode', to='movies_and_shows.season', verbose_name='Сериал'),
        ),
    ]
