# Generated by Django 4.2.15 on 2024-08-30 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies_and_shows', '0002_alter_video_video_season_video_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='movies_and_shows.season', verbose_name='Сериал'),
        ),
    ]
