# Generated by Django 4.2.15 on 2024-08-09 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
