# Generated by Django 4.2.15 on 2024-08-09 08:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_actor_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='dob',
            field=models.DateField(default=datetime.date(2024, 8, 9), verbose_name='Дата Рождения'),
        ),
    ]
