# Generated by Django 4.2.15 on 2024-08-09 08:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_actor_dob'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='url',
        ),
        migrations.AlterField(
            model_name='actor',
            name='dob',
            field=models.DateField(default=datetime.date.today, verbose_name='Дата Рождения'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='world_premiere',
            field=models.DateField(default=datetime.date.today, verbose_name='Премьера в мире'),
        ),
    ]
