# Generated by Django 4.2.15 on 2024-08-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_actor_url_alter_actor_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='url',
            field=models.SlugField(blank=True, max_length=250),
        ),
    ]
