# Generated by Django 4.2.15 on 2024-08-28 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_actor_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ratingstar',
            options={'ordering': ['-value'], 'verbose_name': 'Звезда Рейтинга', 'verbose_name_plural': 'Звезды Рейтинга'},
        ),
    ]
